-- MySQL Script generated by MySQL Workbench
-- 04/23/15 19:34:36
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema coursedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coursedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coursedb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `coursedb` ;

-- -----------------------------------------------------
-- Table `coursedb`.`t_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_user` (
  `id` CHAR(32) NOT NULL,
  `user_name` VARCHAR(255) NULL,
  `user_password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_student` (
  `id` CHAR(32) NOT NULL,
  `t_user_id` CHAR(32) NOT NULL,
  `student_num` VARCHAR(255) NULL, 
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_teacher` (
  `id` CHAR(32) NOT NULL,
  `t_user_id` CHAR(32) NOT NULL,
  `teacher_num` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_teacher_t_user1_idx` (`t_user_id` ASC),
  CONSTRAINT `fk_t_teacher_t_user1`
    FOREIGN KEY (`t_user_id`)
    REFERENCES `coursedb`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_user_basic_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_user_basic_info` (
  `id` CHAR(32) NOT NULL,
  `t_user_id` CHAR(32) NOT NULL,
  `user_contact_info_name` VARCHAR(255) NULL,
  `user_contact_info_birthday` DATETIME NULL,
  `user_contact_info_sex` INT NULL,
  `user_contact_info_address` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_user_basic_info_t_user1_idx` (`t_user_id` ASC),
  CONSTRAINT `fk_t_user_basic_info_t_user1`
    FOREIGN KEY (`t_user_id`)
    REFERENCES `coursedb`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_user_contact_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_user_contact_type` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_login` (
  `id` CHAR(32) NOT NULL,
  `t_user_id` CHAR(32) NOT NULL,
  `login_datetime` DATETIME NOT NULL,
  `login_ip` CHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_login_t_user_idx` (`t_user_id` ASC),
  CONSTRAINT `fk_t_login_t_user`
    FOREIGN KEY (`t_user_id`)
    REFERENCES `coursedb`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_user_contact_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_user_contact_info` (
  `id` CHAR(32) NOT NULL,
  `t_user_id` CHAR(32) NOT NULL,
  `t_user_contact_type_id` CHAR(32) NOT NULL,
  `user_contact_value` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_user_contact_info_t_user1_idx` (`t_user_id` ASC),
  INDEX `fk_t_user_contact_info_t_user_contact_type1_idx` (`t_user_contact_type_id` ASC),
  CONSTRAINT `fk_t_user_contact_info_t_user1`
    FOREIGN KEY (`t_user_id`)
    REFERENCES `coursedb`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_contact_info_t_user_contact_type1`
    FOREIGN KEY (`t_user_contact_type_id`)
    REFERENCES `coursedb`.`t_user_contact_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_school` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_department` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE TABLE `coursedb`.`t_school_department` (
  `id` CHAR(32) NOT NULL,
`t_school_id` CHAR(32) NOT NULL,
`t_department_id` CHAR(32) NOT NULL,
 PRIMARY KEY (`id`),
  INDEX `fk_t_school_department_t_school1_idx` (`t_school_id` ASC),
  INDEX `fk_t_school_department_t_department1_idx` (`t_department_id` ASC),
  CONSTRAINT `fk_t_school_department_t_school1`
    FOREIGN KEY (`t_school_id`)
    REFERENCES `coursedb`.`t_school` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_school_department_t_department1`
    FOREIGN KEY (`t_department_id`)
    REFERENCES `coursedb`.`t_department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

-- -----------------------------------------------------
-- Table `coursedb`.`t_department_teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_department_teacher` (
  `id` CHAR(32) NOT NULL,
  `t_department_id` CHAR(32) NOT NULL,
  `t_teacher_id` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_department_teacher_t_department1_idx` (`t_department_id` ASC),
  INDEX `fk_t_department_teacher_t_teacher1_idx` (`t_teacher_id` ASC),
  CONSTRAINT `fk_t_department_teacher_t_department1`
    FOREIGN KEY (`t_department_id`)
    REFERENCES `coursedb`.`t_department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_department_teacher_t_teacher1`
    FOREIGN KEY (`t_teacher_id`)
    REFERENCES `coursedb`.`t_teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_natural_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_natural_class` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `coursedb`.`t_natural_class_department` (
  `id` CHAR(32) NOT NULL,
  `t_department_id` CHAR(32) NOT NULL,
  `t_natural_class_id` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_natural_class_school_t_department1_idx` (`t_department_id` ASC),
  INDEX `fk_t_natural_class_school_t_natural_class1_idx` (`t_natural_class_id` ASC),
  CONSTRAINT `fk_t_natural_class_school_t_department1`
    FOREIGN KEY (`t_department_id`)
    REFERENCES `coursedb`.`t_department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_natural_class_school_t_natural_class1`
    FOREIGN KEY (`t_natural_class_id`)
    REFERENCES `coursedb`.`t_natural_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_natural_class_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_natural_class_student` (
  `id` CHAR(32) NOT NULL,  
  `t_natural_class_id` CHAR(32) NOT NULL,
  `t_student_id` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`),  
  INDEX `fk_t_natural_class_student_t_t_natural_class1_idx` (`t_natural_class_id` ASC),
  INDEX `fk_t_natural_class_student_t_t_student1_idx` (`t_student_id` ASC),  
  CONSTRAINT `fk_t_natural_class_student_t_natural_class1`
    FOREIGN KEY (`t_natural_class_id`)
    REFERENCES `coursedb`.`t_natural_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_natural_class_student_t_t_student1`
    FOREIGN KEY (`t_student_id`)
    REFERENCES `coursedb`.`t_student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




-- -----------------------------------------------------
-- Table `coursedb`.`t_course_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_type` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_course_style`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_style` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `num` TEXT NOT NULL,
  `english_name` VARCHAR(255) NULL,
  `experiment_hours` INT NOT NULL,
  `class_hours` INT NOT NULL,
  `t_course_style_id` CHAR(32) NOT NULL,
  `t_course_type_id` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
   INDEX `fk_t_course_t_course_style1_idx` (`t_course_style_id` ASC),
  INDEX `fk_t_course_t_course_type1_idx` (`t_course_type_id` ASC),
  CONSTRAINT `fk_t_course_t_course_style1`
    FOREIGN KEY (`t_course_style_id`)
    REFERENCES `coursedb`.`t_course_style` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
     CONSTRAINT `fk_t_course_t_course_type1`
    FOREIGN KEY (`t_course_type_id`)
    REFERENCES `coursedb`.`t_course_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `coursedb`.`t_course_department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_department` (
  `id` CHAR(32) NOT NULL,  
  `t_course_id` CHAR(32) NOT NULL,
  `t_department_id` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
   INDEX `fk_t_course_department_t_course1_idx` (`t_course_id` ASC),
  INDEX `fk_t_course_department_t_department1_idx` (`t_department_id` ASC),
  CONSTRAINT `fk_t_course_department_t_course1`
    FOREIGN KEY (`t_course_id`)
    REFERENCES `coursedb`.`t_course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
     CONSTRAINT `fk_t_course_department_t_department1`
    FOREIGN KEY (`t_department_id`)
    REFERENCES `coursedb`.`t_department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `coursedb`.`t_precourse`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_precourse` (
  `id` CHAR(32) NOT NULL,  
  `t_course_id_this` CHAR(32) NOT NULL,
  `t_course_id_pre` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
   INDEX `fk_t_course_id_t_course1_idx` (`t_course_id_this` ASC),
    INDEX `fk_t_course_id_t_course2_idx` (`t_course_id_pre` ASC),
  
  CONSTRAINT `fk_t_precourse_t_course1`
    FOREIGN KEY (`t_course_id_this`)
    REFERENCES `coursedb`.`t_course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
     CONSTRAINT `fk_t_precourse_t_course2`
    FOREIGN KEY (`t_course_id_pre`)
    REFERENCES `coursedb`.`t_course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `coursedb`.`t_teaching_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_teaching_class` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_course_teaching_class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_teaching_class` (
  `id` CHAR(32) NOT NULL,
  `t_course_id` CHAR(32) NOT NULL,
  `t_teaching_class_id` CHAR(32) NOT NULL,
  `teaching_year_begin` INT NOT NULL,
  `teaching_year_end` INT NOT NULL,
  `teaching_term` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_course_teaching_class_t_course1_idx` (`t_course_id` ASC),
  INDEX `fk_t_course_teaching_class_t_teaching_class1_idx` (`t_teaching_class_id` ASC),
  CONSTRAINT `fk_t_course_teaching_class_t_course1`
    FOREIGN KEY (`t_course_id`)
    REFERENCES `coursedb`.`t_course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_course_teaching_class_t_teaching_class1`
    FOREIGN KEY (`t_teaching_class_id`)
    REFERENCES `coursedb`.`t_teaching_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_teaching_class_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_teaching_class_student` (
  `id` CHAR(32) NOT NULL,
  `t_teaching_class_id` CHAR(32) NOT NULL,
  `t_student_id` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`, `t_teaching_class_id`),
  INDEX `fk_t_teaching_class_student1_idx` (`t_teaching_class_id` ASC),
  INDEX `fk_t_teaching_class_student1_2dx` (`t_student_id` ASC),
  CONSTRAINT `fk_t_teaching_class_student1_idx`
    FOREIGN KEY (`t_teaching_class_id`)
    REFERENCES `coursedb`.`t_teaching_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_teaching_class_student1_2dx`
    FOREIGN KEY (`t_student_id`)
    REFERENCES `coursedb`.`t_student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_teaching_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_teaching_type` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_teaching_class_teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_teaching_class_teacher` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_id` CHAR(32) NOT NULL,
  `t_teacher_id` CHAR(32) NOT NULL,
  `t_teaching_type_id` CHAR(32) NOT NULL,  
  PRIMARY KEY (`id`, `t_teacher_id`),
  INDEX `fk_t_teaching_class_teacher1_idx` (`t_course_teaching_class_id` ASC),
  INDEX `fk_t_teaching_class_teacher2_idx` (`t_teaching_type_id` ASC),
  INDEX `fk_t_teaching_class_teacher3_idx` (`t_teacher_id` ASC),
  CONSTRAINT `fk_t_teaching_class_teacher1_idx`
    FOREIGN KEY (`t_course_teaching_class_id`)
    REFERENCES `coursedb`.`t_course_teaching_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_teaching_class_teacher2_idx`
    FOREIGN KEY (`t_teaching_type_id`)
    REFERENCES `coursedb`.`t_teaching_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_teaching_class_teacher3_idx`
    FOREIGN KEY (`t_teacher_id`)
    REFERENCES `coursedb`.`t_teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_course_teaching_class_reference_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_teaching_class_reference_type` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `note` TEXT NULL,  
  PRIMARY KEY (`id`),
  INDEX `fk_t_course_teaching_class_reference_type_1_idx` (`t_course_teaching_class_id` ASC),
  CONSTRAINT `fk_t_course_teaching_class_reference_type_1_idx`
    FOREIGN KEY (`t_course_teaching_class_id`)
    REFERENCES `coursedb`.`t_course_teaching_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `coursedb`.`t_course_teaching_class_reference`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_teaching_class_reference` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_id` CHAR(32) NOT NULL,
  `t_teacher_id` CHAR(32) NOT NULL,
  `t_course_teaching_class_reference_type_id` VARCHAR(32) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `pubdate` DATETIME NOT NULL,
  `modifieddate` DATETIME NOT NULL,   
  PRIMARY KEY (`id`),
  INDEX `fk_t_course_teaching_class_reference_1_idx` (`t_course_teaching_class_id` ASC),
  INDEX `fk_t_course_teaching_class_reference_2_idx` (`t_teacher_id` ASC),
  INDEX `fk_t_course_teaching_class_reference_3_idx` (`t_course_teaching_class_reference_type_id` ASC),
  CONSTRAINT `fk_t_course_teaching_class_reference_1_idx`
    FOREIGN KEY (`t_course_teaching_class_id`)
    REFERENCES `coursedb`.`t_course_teaching_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_course_teaching_class_reference_2_idx`
    FOREIGN KEY (`t_teacher_id`)
    REFERENCES `coursedb`.`t_teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_course_teaching_class_reference_3_idx`
    FOREIGN KEY (`t_course_teaching_class_reference_type_id`)
    REFERENCES `coursedb`.`t_course_teaching_class_reference_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_course_teaching_class_reference_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_teaching_class_reference_file` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_reference_id` CHAR(32) NOT NULL,
   `filename` VARCHAR(1024) NOT NULL,
  `filepath` VARCHAR(1024) NOT NULL,   
  PRIMARY KEY (`id`),
  INDEX `fk_t_course_teaching_class_reference_file_1_idx` (`t_course_teaching_class_reference_id` ASC), 
  CONSTRAINT `fk_t_course_teaching_class_reference_file_1_idx`
    FOREIGN KEY (`t_course_teaching_class_reference_id`)
    REFERENCES `coursedb`.`t_course_teaching_class_reference` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `coursedb`.`t_course_teaching_class_forum_topic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_teaching_class_forum_topic` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_id` CHAR(32) NOT NULL,
  `t_user_id` CHAR(32) NOT NULL,
   `title` VARCHAR(255) NOT NULL,
  `content` LONGTEXT NULL,
  `created_date` DATETIME NOT NULL,
  `last_modified_date` DATETIME NOT NULL,
  `view_count` INT NOT NULL,
  `flag` INT NOT NULL, 
  PRIMARY KEY (`id`),
  INDEX `fk_t_course_teaching_class_forum_topic1_idx` (`t_course_teaching_class_id` ASC),
  INDEX `fk_t_course_teaching_class_forum_topic2_idx` (`t_user_id` ASC),
  CONSTRAINT `fk_t_course_teaching_class_forum_topic1_idx`
    FOREIGN KEY (`t_course_teaching_class_id`)
    REFERENCES `coursedb`.`t_course_teaching_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_course_teaching_class_forum_topic2_idx`
    FOREIGN KEY (`t_user_id`)
    REFERENCES `coursedb`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_course_teaching_class_forum_topic_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_teaching_class_forum_topic_file` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_forum_topic_id` CHAR(32) NOT NULL,
   `filename` VARCHAR(1024) NOT NULL,
  `filepath` VARCHAR(1024) NOT NULL,   
  PRIMARY KEY (`id`),
  INDEX `fk_t_course_teaching_class_forum_topic_file1_idx` (`t_course_teaching_class_forum_topic_id` ASC), 
  CONSTRAINT `fk_t_course_teaching_class_forum_topic_file1_idx`
    FOREIGN KEY (`t_course_teaching_class_forum_topic_id`)
    REFERENCES `coursedb`.`t_course_teaching_class_forum_topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `coursedb`.`t_course_teaching_class_forum_reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_teaching_class_forum_reply` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_forum_topic_id` CHAR(32) NOT NULL,
  `t_user_id` CHAR(32) NOT NULL,
   `title` VARCHAR(255) NOT NULL,
  `content` LONGTEXT NULL,
  `created_date` DATETIME NOT NULL,
  `last_modified_date` DATETIME NOT NULL,  
  PRIMARY KEY (`id`),
  INDEX `fk_t_course_teaching_class_forum_reply1_idx` (`t_course_teaching_class_forum_topic_id` ASC),
  INDEX `fk_t_course_teaching_class_forum_reply2_idx` (`t_user_id` ASC),
  CONSTRAINT `fk_t_course_teaching_class_forum_reply1_idx`
    FOREIGN KEY (`t_course_teaching_class_forum_topic_id`)
    REFERENCES `coursedb`.`t_course_teaching_class_forum_topic` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_course_teaching_class_forum_reply2_idx`
    FOREIGN KEY (`t_user_id`)
    REFERENCES `coursedb`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_course_teaching_class_forum_reply_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_teaching_class_forum_reply_file` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_forum_reply_id` CHAR(32) NOT NULL,
   `filename` VARCHAR(1024) NOT NULL,
  `filepath` VARCHAR(2014) NOT NULL,   
  PRIMARY KEY (`id`),
  INDEX `fk_t_course_teaching_class_forum_reply_file1_idx` (`t_course_teaching_class_forum_reply_id` ASC), 
  CONSTRAINT `fk_t_course_teaching_class_forum_reply_file1_idx`
    FOREIGN KEY (`t_course_teaching_class_forum_reply_id`)
    REFERENCES `coursedb`.`t_course_teaching_class_forum_reply` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_group` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_user_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_user_group` (
  `id` CHAR(32) NOT NULL,
  `t_group_id` CHAR(32) NOT NULL,
  `t_user_id` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_user_group_t_group1_idx` (`t_group_id` ASC),
  INDEX `fk_t_user_group_t_user1_idx` (`t_user_id` ASC),
  CONSTRAINT `fk_t_user_group_t_group1`
    FOREIGN KEY (`t_group_id`)
    REFERENCES `coursedb`.`t_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_user_group_t_user1`
    FOREIGN KEY (`t_user_id`)
    REFERENCES `coursedb`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_resource` (
  `id` CHAR(32) NOT NULL,
  `uri` VARCHAR(255) NULL,
  `uri_element` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_role` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_group_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_group_role` (
  `id` CHAR(32) NOT NULL,
  `t_group_id` CHAR(32) NOT NULL,
  `t_role_id` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_group_role_t_group1_idx` (`t_group_id` ASC),
  INDEX `fk_t_group_role_t_role1_idx` (`t_role_id` ASC),
  CONSTRAINT `fk_t_group_role_t_group1`
    FOREIGN KEY (`t_group_id`)
    REFERENCES `coursedb`.`t_group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_group_role_t_role1`
    FOREIGN KEY (`t_role_id`)
    REFERENCES `coursedb`.`t_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_permission_operator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_permission_operator` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_permission` (
  `id` CHAR(32) NOT NULL,
  `t_permission_operator_id` CHAR(32) NOT NULL,
  `t_resource_id` CHAR(32) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_permission_t_permission_operator1_idx` (`t_permission_operator_id` ASC),
  INDEX `fk_t_permission_t_resource1_idx` (`t_resource_id` ASC),
  CONSTRAINT `fk_t_permission_t_permission_operator1`
    FOREIGN KEY (`t_permission_operator_id`)
    REFERENCES `coursedb`.`t_permission_operator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_permission_t_resource1`
    FOREIGN KEY (`t_resource_id`)
    REFERENCES `coursedb`.`t_resource` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_role_permission` (
  `id` CHAR(32) NOT NULL,
  `t_role_id` CHAR(32) NOT NULL,
  `t_permission_id` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_role_permission_t_role1_idx` (`t_role_id` ASC),
  INDEX `fk_t_role_permission_t_permission1_idx` (`t_permission_id` ASC),
  CONSTRAINT `fk_t_role_permission_t_role1`
    FOREIGN KEY (`t_role_id`)
    REFERENCES `coursedb`.`t_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_role_permission_t_permission1`
    FOREIGN KEY (`t_permission_id`)
    REFERENCES `coursedb`.`t_permission` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_item_difficulty`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_item_difficulty` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_item_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_item_type` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_item_kinds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_item_kinds` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_database`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_database` (
  `id` CHAR(32) NOT NULL,
  `t_item_difficulty_id` CHAR(32) NOT NULL,
  `t_item_type_id` CHAR(32) NOT NULL,
  `t_item_kinds_id` CHAR(32) NOT NULL,
  `content` LONGTEXT NULL,
  `answer` LONGTEXT NULL,
  `tips` MEDIUMTEXT NULL,
  `solutions` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_database_t_item_difficulty1_idx` (`t_item_difficulty_id` ASC),
  INDEX `fk_t_database_t_item_type1_idx` (`t_item_type_id` ASC),
  INDEX `fk_t_database_t_item_kinds1_idx` (`t_item_kinds_id` ASC),
  CONSTRAINT `fk_t_database_t_item_difficulty1`
    FOREIGN KEY (`t_item_difficulty_id`)
    REFERENCES `coursedb`.`t_item_difficulty` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_database_t_item_type1`
    FOREIGN KEY (`t_item_type_id`)
    REFERENCES `coursedb`.`t_item_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_database_t_item_kinds1`
    FOREIGN KEY (`t_item_kinds_id`)
    REFERENCES `coursedb`.`t_item_kinds` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_course_database`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_database` (
  `id` CHAR(32) NOT NULL,
  `t_database_id` CHAR(32) NOT NULL,
  `t_user_id` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_course_database_t_database1_idx` (`t_database_id` ASC),
  INDEX `fk_t_course_database_t_user1_idx` (`t_user_id` ASC),
  CONSTRAINT `fk_t_course_database_t_database1`
    FOREIGN KEY (`t_database_id`)
    REFERENCES `coursedb`.`t_database` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_course_database_t_user1`
    FOREIGN KEY (`t_user_id`)
    REFERENCES `coursedb`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_logging_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_database_logging_type` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_database_logging`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_database_logging` (
  `id` CHAR(32) NOT NULL,
  `t_database_id` CHAR(32) NOT NULL,
  `t_user_id` CHAR(32) NOT NULL,
  `t_database_logging_type_id` CHAR(32) NOT NULL,
  `logging_datetime` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_database_log_t_database1_idx` (`t_database_id` ASC),
  INDEX `fk_t_database_log_t_user1_idx` (`t_user_id` ASC),
  INDEX `fk_t_database_log_t_database_logging_type1_idx` (`t_database_logging_type_id` ASC),
  CONSTRAINT `fk_t_database_log_t_database1`
    FOREIGN KEY (`t_database_id`)
    REFERENCES `coursedb`.`t_database` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_database_log_t_user1`
    FOREIGN KEY (`t_user_id`)
    REFERENCES `coursedb`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_database_log_t_database_logging_type1`
    FOREIGN KEY (`t_database_logging_type_id`)
    REFERENCES `coursedb`.`t_database_logging_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_knowledgepoint_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_knowledgepoint_type` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_knowledgepoint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_knowledgepoint` (
  `id` CHAR(32) NOT NULL,
  `content` LONGTEXT NULL,
  `name` VARCHAR(255) NULL,
  `t_knowledgepoint_type_id` CHAR(32) NOT NULL,
  `t_item_difficulty_id` CHAR(32) NOT NULL,
  `father` CHAR(32) NULL,
  `next` CHAR(32) NULL,
  `t_knowledgepointcol` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_knowledgepoint_t_knowledgepoint_type1_idx` (`t_knowledgepoint_type_id` ASC),
  INDEX `fk_t_knowledgepoint_t_item_difficulty1_idx` (`t_item_difficulty_id` ASC),
  CONSTRAINT `fk_t_knowledgepoint_t_knowledgepoint_type1`
    FOREIGN KEY (`t_knowledgepoint_type_id`)
    REFERENCES `coursedb`.`t_knowledgepoint_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_knowledgepoint_t_item_difficulty1`
    FOREIGN KEY (`t_item_difficulty_id`)
    REFERENCES `coursedb`.`t_item_difficulty` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_database_knowledgepoint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_database_knowledgepoint` (
  `id` CHAR(32) NOT NULL,
  `t_knowledgepoint_id` CHAR(32) NOT NULL,
  `t_database_id` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_database_knowledgepoint_t_knowledgepoint1_idx` (`t_knowledgepoint_id` ASC),
  INDEX `fk_t_database_knowledgepoint_t_database1_idx` (`t_database_id` ASC),
  CONSTRAINT `fk_t_database_knowledgepoint_t_knowledgepoint1`
    FOREIGN KEY (`t_knowledgepoint_id`)
    REFERENCES `coursedb`.`t_knowledgepoint` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_database_knowledgepoint_t_database1`
    FOREIGN KEY (`t_database_id`)
    REFERENCES `coursedb`.`t_database` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_score_system_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_score_system_type` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_course_teaching_class_homework_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_teaching_class_homework_type` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `note` TEXT NULL,  
  PRIMARY KEY (`id`),
  INDEX `fk_t_homework_type_1_idx` (`t_course_teaching_class_id` ASC),
  CONSTRAINT `fk_t_homework_type_1_idx`
    FOREIGN KEY (`t_course_teaching_class_id`)
    REFERENCES `coursedb`.`t_course_teaching_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `coursedb`.`t_course_teaching_class_homework_baseinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_teaching_class_homework_baseinfo` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_id` CHAR(32) NOT NULL,
  `t_teacher_id` CHAR(32) NOT NULL,
  `t_course_teaching_class_homework_type_id` CHAR(32) NOT NULL,
  `filetype` TEXT NOT NULL,
  `filenameformat` TEXT NOT NULL,
  `filecount` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` LONGTEXT NULL,
  `pubdate` DATETIME NOT NULL,
  `enddate` DATETIME NOT NULL,   
  PRIMARY KEY (`id`),
  INDEX `fk_t_course_teaching_class_homework_baseinfo_1_idx` (`t_course_teaching_class_id` ASC),
  INDEX `fk_t_course_teaching_class_homework_baseinfo_2_idx` (`t_teacher_id` ASC),
  INDEX `fk_t_course_teaching_class_homework_baseinfo_3_idx` (`t_course_teaching_class_homework_type_id` ASC),
  CONSTRAINT `fk_t_course_teaching_class_homework_baseinfo_1_idx`
    FOREIGN KEY (`t_course_teaching_class_id`)
    REFERENCES `coursedb`.`t_course_teaching_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_course_teaching_class_homework_baseinfo_2_idx`
    FOREIGN KEY (`t_teacher_id`)
    REFERENCES `coursedb`.`t_teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_course_teaching_class_homework_baseinfo_3_idx`
    FOREIGN KEY (`t_course_teaching_class_homework_type_id`)
    REFERENCES `coursedb`.`t_course_teaching_class_homework_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_course_teaching_class_homework_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_teaching_class_homework_file` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_homework_baseinfo_id` CHAR(32) NOT NULL,
   `filename` VARCHAR(1024) NOT NULL,
  `filepath` VARCHAR(1024) NOT NULL,   
  PRIMARY KEY (`id`),
  INDEX `fk_t_course_teaching_class_homework_file_1_idx` (`t_course_teaching_class_homework_baseinfo_id` ASC), 
  CONSTRAINT `fk_t_course_teaching_class_homework_file_1_idx`
    FOREIGN KEY (`t_course_teaching_class_homework_baseinfo_id`)
    REFERENCES `coursedb`.`t_course_teaching_class_homework_baseinfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_course_teaching_class_homework_score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_teaching_class_homework_score` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_homework_baseinfo_id` CHAR(32) NOT NULL,
  `t_score_system_type_id` VARCHAR(32) NOT NULL,
   `score` VARCHAR(32) NOT NULL,     
  PRIMARY KEY (`id`),
  INDEX `fk_t_course_teaching_class_homework_score_1_idx` (`t_course_teaching_class_homework_baseinfo_id` ASC), 
  INDEX `fk_t_course_teaching_class_homework_score_2_idx` (`t_score_system_type_id` ASC),
  CONSTRAINT `fk_t_course_teaching_class_homework_score_1_idx`
    FOREIGN KEY (`t_course_teaching_class_homework_baseinfo_id`)
    REFERENCES `coursedb`.`t_course_teaching_class_homework_baseinfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_t_course_teaching_class_homework_score_2_idx`
    FOREIGN KEY (`t_score_system_type_id`)
    REFERENCES `coursedb`.`t_score_system_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_course_teaching_class_homework_delayed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_teaching_class_homework_delayed` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_homework_baseinfo_id` CHAR(32) NOT NULL,
   `t_teacher_id` CHAR(32) NOT NULL,
   `pubdate` DATETIME NOT NULL,
  `enddate` DATETIME NOT NULL,   
  PRIMARY KEY (`id`),
  INDEX `fk_t_course_teaching_class_homework_delayed_1_idx` (`t_course_teaching_class_homework_baseinfo_id` ASC), 
  INDEX `fk_t_course_teaching_class_homework_delayed_2_idx` (`t_teacher_id` ASC),
  CONSTRAINT `fk_t_course_teaching_class_homework_delayed_1_idx`
    FOREIGN KEY (`t_course_teaching_class_homework_baseinfo_id`)
    REFERENCES `coursedb`.`t_course_teaching_class_homework_baseinfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
     CONSTRAINT `fk_t_course_teaching_class_homework_delayed_2_idx`
    FOREIGN KEY (`t_teacher_id`)
    REFERENCES `coursedb`.`t_teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_course_teaching_class_homework_submit_baseinfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_teaching_class_homework_submit_baseinfo` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_homework_baseinfo_id` CHAR(32) NOT NULL,
  `t_student_id` CHAR(32) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` LONGTEXT NULL,
  `submitdate` DATETIME NOT NULL,
  `modifieddate` DATETIME NOT NULL,   
  PRIMARY KEY (`id`),
  INDEX `fk_t_course_teaching_class_homework_submit_baseinfo_1_idx` (`t_course_teaching_class_homework_baseinfo_id` ASC),
  INDEX `fk_t_course_teaching_class_homework_submit_baseinfo_2_idx` (`t_student_id` ASC),
  CONSTRAINT `fk_t_course_teaching_class_homework_submit_baseinfo_1_idx`
    FOREIGN KEY (`t_course_teaching_class_homework_baseinfo_id`)
    REFERENCES `coursedb`.`t_course_teaching_class_homework_baseinfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_course_teaching_class_homework_submit_baseinfo_2_idx`
    FOREIGN KEY (`t_student_id`)
    REFERENCES `coursedb`.`t_student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_course_teaching_class_homework_submit_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_teaching_class_homework_submit_file` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_homework_submit_baseinfo_id` CHAR(32) NOT NULL,
   `filename` VARCHAR(1024) NOT NULL,
  `filepath` VARCHAR(1024) NOT NULL,   
  PRIMARY KEY (`id`),
  INDEX `fk_t_course_teaching_class_homework_submit_file_1_idx` (`t_course_teaching_class_homework_submit_baseinfo_id` ASC), 
  CONSTRAINT `fk_t_course_teaching_class_homework_submit_file_1_idx`
    FOREIGN KEY (`t_course_teaching_class_homework_submit_baseinfo_id`)
    REFERENCES `coursedb`.`t_course_teaching_class_homework_submit_baseinfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_course_teaching_class_homework_reply`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_teaching_class_homework_reply` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_homework_submit_baseinfo_id` CHAR(32) NOT NULL,
  `t_teacher_id` VARCHAR(32) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` LONGTEXT NULL,
  `submitdate` DATETIME NOT NULL,
  `modifieddate` DATETIME NOT NULL,   
  PRIMARY KEY (`id`),
  INDEX `fk_t_course_teaching_class_homework_reply_1_idx` (`t_course_teaching_class_homework_submit_baseinfo_id` ASC),
  INDEX `fk_t_course_teaching_class_homework_reply_2_idx` (`t_teacher_id` ASC),
  CONSTRAINT `fk_t_course_teaching_class_homework_reply_1_idx`
    FOREIGN KEY (`t_course_teaching_class_homework_submit_baseinfo_id`)
    REFERENCES `coursedb`.`t_course_teaching_class_homework_submit_baseinfo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_course_teaching_class_homework_reply_2_idx`
    FOREIGN KEY (`t_teacher_id`)
    REFERENCES `coursedb`.`t_teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_course_teaching_class_homework_reply_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_course_teaching_class_homework_reply_file` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_homework_reply_id` CHAR(32) NOT NULL,
   `filename` VARCHAR(1024) NOT NULL,
  `filepath` VARCHAR(1024) NOT NULL,   
  PRIMARY KEY (`id`),
  INDEX `fk_t_course_teaching_class_homework_reply_file_1_idx` (`t_course_teaching_class_homework_reply_id` ASC), 
  CONSTRAINT `fk_t_course_teaching_class_homework_reply_file_1_idx`
    FOREIGN KEY (`t_course_teaching_class_homework_reply_id`)
    REFERENCES `coursedb`.`t_course_teaching_class_homework_reply` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `coursedb`.`t_examination_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_examination_type` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_examination_constitution_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_examination_constitution_type` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_examination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_examination` (
  `id` CHAR(32) NOT NULL,
  `t_teacher_id` CHAR(32) NOT NULL,
  `t_examination_type_id` CHAR(32) NOT NULL,
  `total_score` VARCHAR(45) NULL,
  `begin_datetime` DATETIME NULL,
  `end_datetime` DATETIME NULL,
  `t_course_id` CHAR(32) NOT NULL,
  `t_examination_constitution_type_id` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_examination_t_teacher1_idx` (`t_teacher_id` ASC),
  INDEX `fk_t_examination_t_examination_type1_idx` (`t_examination_type_id` ASC),
  INDEX `fk_t_examination_t_course1_idx` (`t_course_id` ASC),
  INDEX `fk_t_examination_t_examination_constitution_type1_idx` (`t_examination_constitution_type_id` ASC),
  CONSTRAINT `fk_t_examination_t_teacher1`
    FOREIGN KEY (`t_teacher_id`)
    REFERENCES `coursedb`.`t_teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_examination_t_examination_type1`
    FOREIGN KEY (`t_examination_type_id`)
    REFERENCES `coursedb`.`t_examination_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_examination_t_course1`
    FOREIGN KEY (`t_course_id`)
    REFERENCES `coursedb`.`t_course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_examination_t_examination_constitution_type1`
    FOREIGN KEY (`t_examination_constitution_type_id`)
    REFERENCES `coursedb`.`t_examination_constitution_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_examination_database`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_examination_database` (
  `id` CHAR(32) NOT NULL,
  `t_examination_id` CHAR(32) NOT NULL,
  `t_database_id` CHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_examination_database_t_examination1_idx` (`t_examination_id` ASC),
  INDEX `fk_t_examination_database_t_database1_idx` (`t_database_id` ASC),
  CONSTRAINT `fk_t_examination_database_t_examination1`
    FOREIGN KEY (`t_examination_id`)
    REFERENCES `coursedb`.`t_examination` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_examination_database_t_database1`
    FOREIGN KEY (`t_database_id`)
    REFERENCES `coursedb`.`t_database` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_score` (
  `id` CHAR(32) NOT NULL,
  `t_student_id` CHAR(32) NOT NULL,
  `t_course_id` CHAR(32) NOT NULL,
  `t_examination_id` CHAR(32) NOT NULL,
  `score` FLOAT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_score_t_student1_idx` (`t_student_id` ASC),
  INDEX `fk_t_score_t_course1_idx` (`t_course_id` ASC),
  INDEX `fk_t_score_t_examination1_idx` (`t_examination_id` ASC),
  CONSTRAINT `fk_t_score_t_student1`
    FOREIGN KEY (`t_student_id`)
    REFERENCES `coursedb`.`t_student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_score_t_course1`
    FOREIGN KEY (`t_course_id`)
    REFERENCES `coursedb`.`t_course` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_score_t_examination1`
    FOREIGN KEY (`t_examination_id`)
    REFERENCES `coursedb`.`t_examination` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_score_constitution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_score_constitution` (
  `id` CHAR(32) NOT NULL,
  `t_score_id` CHAR(32) NOT NULL,
  `percent` INT NULL,
  `note` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_score_constitution_t_score1_idx` (`t_score_id` ASC),
  CONSTRAINT `fk_t_score_constitution_t_score1`
    FOREIGN KEY (`t_score_id`)
    REFERENCES `coursedb`.`t_score` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_examination_constitution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_examination_constitution` (
  `id` CHAR(32) NOT NULL,
  `t_examination_id` CHAR(32) NOT NULL,
  `t_item_type_id` CHAR(32) NOT NULL,
  `item_count` INT NULL,
  `percent` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_examination_constitution_t_examination1_idx` (`t_examination_id` ASC),
  INDEX `fk_t_examination_constitution_t_item_type1_idx` (`t_item_type_id` ASC),
  CONSTRAINT `fk_t_examination_constitution_t_examination1`
    FOREIGN KEY (`t_examination_id`)
    REFERENCES `coursedb`.`t_examination` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_examination_constitution_t_item_type1`
    FOREIGN KEY (`t_item_type_id`)
    REFERENCES `coursedb`.`t_item_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;








-- -----------------------------------------------------
-- Table `coursedb`.`t_knowledgepoint_logging`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_knowledgepoint_logging` (
  `id` CHAR(32) NOT NULL,
  `t_database_knowledgepoint_id` CHAR(32) NOT NULL,
  `t_user_id` CHAR(32) NOT NULL,
  `t_logging_type_id` CHAR(32) NOT NULL,
  `t_knowledgepoint_id` CHAR(32) NOT NULL,
  `logging_datetime` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_knowledgepoint_logging_t_database_knowledgepoint1_idx` (`t_database_knowledgepoint_id` ASC),
  INDEX `fk_t_knowledgepoint_logging_t_user1_idx` (`t_user_id` ASC),
  INDEX `fk_t_knowledgepoint_logging_t_logging_type1_idx` (`t_logging_type_id` ASC),
  INDEX `fk_t_knowledgepoint_logging_t_knowledgepoint1_idx` (`t_knowledgepoint_id` ASC),
  CONSTRAINT `fk_t_knowledgepoint_logging_t_database_knowledgepoint1`
    FOREIGN KEY (`t_database_knowledgepoint_id`)
    REFERENCES `coursedb`.`t_database_knowledgepoint` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_knowledgepoint_logging_t_user1`
    FOREIGN KEY (`t_user_id`)
    REFERENCES `coursedb`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_knowledgepoint_logging_t_logging_type1`
    FOREIGN KEY (`t_logging_type_id`)
    REFERENCES `coursedb`.`t_logging_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_knowledgepoint_logging_t_knowledgepoint1`
    FOREIGN KEY (`t_knowledgepoint_id`)
    REFERENCES `coursedb`.`t_knowledgepoint` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;





-- -----------------------------------------------------
-- Table `coursedb`.`t_attendance_state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_attendance_state` (
  `id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_attendance_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_attendance_type` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_id` CHAR(32) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `note` TEXT NULL,  
  PRIMARY KEY (`id`),
  INDEX `fk_t_attendance_type_1_idx` (`t_course_teaching_class_id` ASC),
  CONSTRAINT `fk_t_attendance_type_1_idx`
    FOREIGN KEY (`t_course_teaching_class_id`)
    REFERENCES `coursedb`.`t_course_teaching_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `coursedb`.`t_attendance_mode`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_attendance_mode` (
  `id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(255) NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_attendance` (
  `id` CHAR(32) NOT NULL,
  `t_course_teaching_class_id` CHAR(32) NOT NULL,
  `t_attendance_type_id` CHAR(32) NOT NULL,
  `t_teacher_id` CHAR(32) NOT NULL,
  `begin_datetime` DATETIME NULL,
  `end_datetime` DATETIME NULL,
  `note` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_attendance_t_course_teaching_class1_idx` (`t_course_teaching_class_id` ASC),
  INDEX `fk_t_attendance_t_attendance_type1_idx` (`t_attendance_type_id` ASC),
  INDEX `fk_t_attendance_t_teacher1_idx` (`t_teacher_id` ASC),
  CONSTRAINT `fk_t_attendance_t_course_teaching_class1`
    FOREIGN KEY (`t_course_teaching_class_id`)
    REFERENCES `coursedb`.`t_course_teaching_class` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
   CONSTRAINT `fk_t_attendance_t_attendance_type1_idx`
    FOREIGN KEY (`t_attendance_type_id`)
    REFERENCES `coursedb`.`t_attendance_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_attendance_t_teacher1`
    FOREIGN KEY (`t_teacher_id`)
    REFERENCES `coursedb`.`t_teacher` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_attendance_student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_attendance_student` (
  `id` CHAR(32) NOT NULL,
  `t_attendance_id` CHAR(32) NOT NULL,
  `t_student_id` CHAR(32) NOT NULL,
  `t_attendance_state_id` CHAR(32) NOT NULL,
   `t_attendance_mode_id` CHAR(32) NOT NULL,
   `checking_in_datetime` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_attendance_student_t_attendance1_idx` (`t_attendance_id` ASC),
  INDEX `fk_t_attendance_student_t_student1_idx` (`t_student_id` ASC),
  INDEX `fk_t_attendance_student_t_attendance_mode1_idx` (`t_attendance_mode_id` ASC),
  CONSTRAINT `fk_t_attendance_student_t_attendance1`
    FOREIGN KEY (`t_attendance_id`)
    REFERENCES `coursedb`.`t_attendance` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_attendance_student_t_student1`
    FOREIGN KEY (`t_student_id`)
    REFERENCES `coursedb`.`t_student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_attendance_student_t_attendance_state1`
    FOREIGN KEY (`t_attendance_state_id`)
    REFERENCES `coursedb`.`t_attendance_state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION, 
  CONSTRAINT `fk_t_attendance_student_t_attendance_mode1`
    FOREIGN KEY (`t_attendance_mode_id`)
    REFERENCES `coursedb`.`t_attendance_mode` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_mail_box_send`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_mail_box_send` (
  `id` CHAR(32) NOT NULL,
  `t_user_id_from` CHAR(32) NOT NULL,
  `t_user_id_to` CHAR(32) NOT NULL,
  `state` VARCHAR(255) NOT NULL,
  `subject` VARCHAR(255) NOT NULL,
  `content` LONGTEXT NULL,
  `senddate` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_mail_box_send_1_idx` (`t_user_id_from` ASC),
  INDEX `fk_t_mail_box_send_2_idx` (`t_user_id_to` ASC), 
  CONSTRAINT `fk_t_mail_box_send_1_idx`
    FOREIGN KEY (`t_user_id_from`)
    REFERENCES `coursedb`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_mail_box_send_2_idx`
    FOREIGN KEY (`t_user_id_to`)
    REFERENCES `coursedb`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_mail_box_send_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_mail_box_send_file` (
  `id` CHAR(32) NOT NULL,
  `t_mail_box_send_id` CHAR(32) NOT NULL,
   `filename` VARCHAR(1024) NOT NULL,
  `filepath` VARCHAR(1024) NOT NULL,   
  PRIMARY KEY (`id`),
  INDEX `fk_t_mail_box_send_file_1_idx` (`t_mail_box_send_id` ASC), 
  CONSTRAINT `fk_t_mail_box_send_file_1_idx`
    FOREIGN KEY (`t_mail_box_send_id`)
    REFERENCES `coursedb`.`t_mail_box_send` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `coursedb`.`t_mail_box_received`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_mail_box_received` (
  `id` CHAR(32) NOT NULL,
  `t_user_id_from` CHAR(32) NOT NULL,
  `t_user_id_to` CHAR(32) NOT NULL,
  `state` VARCHAR(255) NOT NULL,
  `subject` VARCHAR(255) NOT NULL,
  `content` LONGTEXT NULL,
  `senddate` DATETIME NOT NULL,
  `readdate` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_t_mail_received_box_1_idx` (`t_user_id_from` ASC),
  INDEX `fk_t_mail_received_box_2_idx` (`t_user_id_to` ASC), 
  CONSTRAINT `fk_t_mail_received_box_1_idx`
    FOREIGN KEY (`t_user_id_from`)
    REFERENCES `coursedb`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_mail_received_box_2_idx`
    FOREIGN KEY (`t_user_id_to`)
    REFERENCES `coursedb`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coursedb`.`t_mail_box_received_file`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`t_mail_box_received_file` (
  `id` CHAR(32) NOT NULL,
  `t_mail_box_received_id` CHAR(32) NOT NULL,
   `filename` VARCHAR(1024) NOT NULL,
  `filepath` VARCHAR(1024) NOT NULL,   
  PRIMARY KEY (`id`),
  INDEX `fk_t_mail_box_received_file_1_idx` (`t_mail_box_received_id` ASC), 
  CONSTRAINT `fk_t_mail_box_received_file_1_idx`
    FOREIGN KEY (`t_mail_box_received_id`)
    REFERENCES `coursedb`.`t_mail_box_received` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
